version: '3'

silent: true

tasks:

  build:
    cmds:
      - cmd: npm run build

  start:
    cmds:
      - cmd: npm run build
      - cmd: npm run start

  serve:
    cmds:
      - cmd: npm run dev
